---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 99-apps
  namespace: flux-system
spec:
  interval: 10m0s
  suspend: false
  dependsOn:
    - name: 10-infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  prune: true
  wait: true
  timeout: 5m0s
