---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  suspend: true
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 10-infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: 01-infra-controllers
  interval: 1h
  suspend: true
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  patches: [] # test! staging! the patch below is only for production

    # - patch: |
    #     - op: replace
    #       path: /spec/acme/server
    #       value: https://acme-v02.api.letsencrypt.org/directory
    #   target:
    #     kind: ClusterIssuer
    #     name: letsencrypt
