---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-docs
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/kingdon-ci/flux-docs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-docs
  namespace: flux-system
spec:
  timeout: 2m0s
  retryInterval: 2m30s
  suspend: true
  interval: 10m0s
  path: ./kustomize-flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-docs
