apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 03-ingress-nginx
  namespace: flux-system
spec:
  interval: 2m30s
  timeout: 2m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  storageNamespace: ingress-nginx
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      version: '4.x'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 15m
  values:
    controller:
      extraArgs: {}
        # enable-ssl-passthrough: ""
        # ingress-class: public
      # electionID: public-ingress-leader
      # ingressClassResource:
      #   name: public
      #   default: true
      #   controllerValue: "k8s.io/ingress-nginx-public"
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: "true"
      #     namespace: grafana
      #     namespaceSelector:
      #       matchNames:
      #         - ingress-nginx
