apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: simple.test.moomboo.space
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: simple-spinapp
            port:
              number: 80
